name: ts_forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.11.8
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - alembic==1.13.1
      - aniso8601==9.0.1
      - blinker==1.7.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - docker==7.0.0
      - flask==3.0.2
      - fonttools==4.50.0
      - gluonts==0.14.4
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - gunicorn==21.2.0
      - idna==3.6
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lightning==2.1.4
      - lightning-utilities==0.11.0
      - mako==1.3.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mlflow==2.11.3
      - mpmath==1.3.0
      - mxnet==1.9.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - optuna==3.6.0
      - packaging==23.2
      - pandas==2.1.4
      - pillow==10.2.0
      - protobuf==4.25.3
      - pyarrow==15.0.2
      - pyparsing==3.1.2
      - python-graphviz==0.8.4
      - pytorch-lightning==2.1.4
      - pytz==2024.1
      - pyyaml==6.0.1
      - querystring-parser==1.2.4
      - requests==2.31.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - seaborn==0.13.2
      - sqlalchemy==2.0.28
      - sqlparse==0.4.4
      - sympy==1.12
      - threadpoolctl==3.4.0
      - toolz==0.12.1
      - torch==2.2.1
      - torchmetrics==1.3.2
      - triton==2.2.0
      - urllib3==2.2.1
      - werkzeug==3.0.1
