name: ts_forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - archspec=0.2.3
  - asttokens=2.4.1
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - comm=0.2.2
  - conda=24.1.2
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - distro=1.8.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fmt=9.1.0
  - icu=73.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=1.5.6
  - libmambapy=1.5.6
  - libnghttp2=1.57.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - menuinst=2.0.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - packaging=24.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.2.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pyzmq=25.1.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.2
  - truststore=0.8.0
  - typing_extensions=4.10.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - alembic==1.13.1
      - aniso8601==9.0.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - attrs==23.2.0
      - blinker==1.7.0
      - blis==0.7.11
      - catalogue==2.0.10
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - confection==0.1.4
      - contourpy==1.2.0
      - cycler==0.12.1
      - cymem==2.0.8
      - cython==3.0.9
      - docker==7.0.0
      - entrypoints==0.4
      - fastai==2.7.14
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - filelock==3.13.1
      - flask==3.0.2
      - fonttools==4.50.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gluonts==0.14.4
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - gunicorn==21.2.0
      - hydra-core==1.3.2
      - idna==3.6
      - imbalanced-learn==0.12.0
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - lightning==2.1.4
      - lightning-utilities==0.11.0
      - llvmlite==0.42.0
      - mako==1.3.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mlflow==2.11.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - murmurhash==1.0.10
      - mxnet==1.9.1
      - networkx==3.2.1
      - numba==0.59.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - optuna==3.6.0
      - pandas==2.1.4
      - patsy==0.5.6
      - pillow==10.2.0
      - pip==24.0
      - pmdarima==2.0.4
      - preshed==3.0.9
      - protobuf==4.25.3
      - pyarrow==15.0.2
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pyparsing==3.1.2
      - python-graphviz==0.8.4
      - pytorch-lightning==2.1.4
      - pyts==0.13.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - querystring-parser==1.2.4
      - scikit-base==0.7.5
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - seaborn==0.13.2
      - sktime==0.27.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.28
      - sqlparse==0.4.4
      - srsly==2.4.8
      - statsmodels==0.14.1
      - sympy==1.12
      - thinc==8.2.3
      - threadpoolctl==3.4.0
      - toolz==0.12.1
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchmetrics==1.3.2
      - torchvision==0.17.1
      - triton==2.2.0
      - tsai==0.3.9
      - typer==0.9.4
      - tzdata==2024.1
      - urllib3==2.2.1
      - wasabi==1.1.2
      - weasel==0.3.4
      - werkzeug==3.0.1
      - xgboost==2.0.3
      - yarl==1.9.4
