DataLoader:
  _target_: codes.dataset.Dataset.Dataset

data_params:
  station_name: 'Shunyi'
  # 'Shunyi', 'Dongsi', 'Dingling', 'Wanshouxigong', 'Huairou',
  # 'Wanliu', 'Aotizhongxin', 'Gucheng', 'Nongzhanguan', 'Tiantan',
  # 'Guanyuan', 'Changping'
  target: 'PM2.5' # 'PM2.5', 'PM10', 'TEMP'
  standardize: True
  get_year: True
  get_month: True
  window_size: 24
  forecast_horizon: 5
  granularity: 'hourly' # 'hourly', 'daily', 'weekly', 'monthly'
  test_ratio: 0.2
  for_tsai: True

