model_params:
  _target_: codes.dataset.Dataset.Dataset

data_params:
  station_name: 'Shunyi'
  # 'Shunyi', 'Dongsi', 'Dingling', 'Wanshouxigong', 'Huairou',
  # 'Wanliu', 'Aotizhongxin', 'Gucheng', 'Nongzhanguan', 'Tiantan',
  # 'Guanyuan', 'Changping'
  target: 'PM25' # 'PM25', 'PM10', 'O3', 'NO2', 'CO', 'SO2'
  normalize: False
  window_size: 5
  forecast_horizon: 5
  granularity: 'hourly' # 'hourly', 'daily', 'weekly', 'monthly'
  test_ratio: 0.2

