name: get-best-runs

on:
  push:
    branches:
      - master

jobs:
  get-best-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow python-git

      - name: Run script
        run: python3 utils/best_results.py

      - name: Set Git Config
        run: |
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git config --global user.name "${{ secrets.MY_NAME }}"

      - name: Commit results if it changed
        run: |
          # if the results changed then commit the changes
          if [[ $(git status --porcelain) ]]; then
            git add utils/best_results.txt
            git commit -m "Update best results"
            git push
          fi